### PR TITLE
Add support for automatic building, also creating arm32 and arm64 versions

### PR DESCRIPTION
**Pull request by GioF71**
Hello, I cloned your repo because I wanted to create arm versions of your image.
Also, I wanted to have multiple versions of the image. For example, the workflow can be extended so (for example), when a new debian stable version comes out, you might still want to regularly build an image with bullseye and another build with the current stable, at least for a while.
The workflow requires as you can imagine these two secrets:

DOCKER_USERNAME
DOCKER_PASSWORD

You can have a look at the resulting builds here:
https://hub.docker.com/repository/docker/giof71/apt-cacher-ng/tags?page=1&ordering=last_updated

EDIT: link to builds was missing, reviewed description

### CODE REVIEW

**Comment by mbentley** [comment]
I can easily add multi-arch support.  I do all of my builds using Jenkins on my own infrastructure and all of my Jenkinsfiles are in a private repo.  It's a low lift to do so ([images now on Docker Hub w/multi-arch](https://hub.docker.com/repository/docker/mbentley/apt-cacher-ng/tags?page=1&ordering=last_updated))

When you said:
 > Also, I wanted to have multiple versions of the image. For example, the workflow can be extended so (for example), when a new debian stable version comes out, you might still want to regularly build an image with bullseye and another build with the current stable

For having different versions, the best option that doesn't require additional work would be to have a `bullseye` based image and then a `sid` based image to pull in the latest available [packaged versions](https://packages.debian.org/search?arch=amd64&searchon=names&keywords=apt-cacher-ng).  At least that is how I would do it to keep it simple so manually updating a file isn't necessary and it can be assumed that each version would have the latest version in each suite.

**Comment by GioF71** [comment]
Thank you for building with arm/arm64, that's excellent news. I have a raspberry pi at another location and I had to use another image because yours did not have the arm version. So thanks a lot.
I already saw you have multiarch images in your repos so I had not doubt you could easily add the feature.
About writing the apt-cacher-ng version on the workflow, that's not particulary important, it was just an example of setting tag names if needed.
I believe it would be better to have other older versions along with an updated `latest` available on docker hub, just in case of a regression after an upgrade. Of course I can solve this problem for me by tagging a version and saving it on my docker registry instance, still it would be nice to have if you agree.
Regressions are probably very unlikely to happen on apt-cacher-ng, but in general, it would be nice to be able to revert to a previous well-know version which works properly.
Thank you for you attention.

p.s. I have no particular interest in maintaining the github and docker hub repos, especially considering I did not add any particular value to your work now that you have made arm versions available. And of course, thank you for your work. I have been using your container for more than a year now with great satisfaction.

**Comment by mbentley** [comment]
I've done something similar with [mbentley/timemachine with date specific tags](https://github.com/mbentley/docker-timemachine#date-specific-tags).  If that is helpful, I could implement that here as well.

**Comment by GioF71** [comment]
Yes, that would be perfect!
Thank you!

**Comment by mbentley** [comment]
OK, I've implemented tags with dates using manifests which will run daily:

```
docker manifest rm mbentley/apt-cacher-ng:latest-$(date +%Y%m%d) || true'
docker manifest create mbentley/apt-cacher-ng:latest-$(date +%Y%m%d) --amend mbentley/apt-cacher-ng:latest-amd64 --amend mbentley/apt-cacher-ng:latest-arm64 --amend mbentley/apt-cacher-ng:latest-armv7l'
docker manifest push --purge mbentley/apt-cacher-ng:latest-$(date +%Y%m%d)'
```

README was updated in #2 along with the 6 month pruning script.

**Comment by GioF71** [comment]
Great work, thank you!

**Pull request closed without merging**
